(:id "immortal-coil/base"
 :name "Immortal Coil"
 :version "0.0.1"
 :description "Bundled story graph."
 :depends-on ()
 :scripts ("maze/minigame.lisp"
           "maze/audio.lisp"
           "maze/rendering.lisp"
           "flight/minigame.lisp"
           "flight/rendering.lisp"
           "rogue/delve.lisp"
           "war/radio.lisp"
           "war/audit.lisp"
           "forest/hide.lisp"
           "jrpg/state.lisp"
           "jrpg/combat.lisp"
           "jrpg/overworld.lisp"
           "opening.lisp"
           "campaign/forest.lisp"
           "campaign/jrpg.lisp"
           "campaign/dream-worlds.lisp"
           "campaign/war.lisp"
           "campaign/containment.lisp"
           "campaign/husk.lisp"
           "campaign/mutiny.lisp"
           "campaign/district.lisp"
           "campaign/tribunal.lisp"
           "editor-drafts.lisp")
 :assets "../assets/"
 :title-logo "logo/title-logo.png"
 :start "base/awake")
