(in-package #:immortal-coil)

(-> load-audio () t)
(defun load-audio ()
  (configure-music-stream-buffer)
  (load-type-clicks)
  (load-choice-switch)
  (load-start-confirm)
  (load-title-music))

(-> update-bgm-streams () t)
(defun update-bgm-streams ()
  (sync-story-music-volume)
  (update-story-music-stream)
  (update-title-music-stream))

(-> clear-audio-resources () t)
(defun clear-audio-resources ()
  (clear-story-sound-resources)
  (clear-story-music-resources)
  (clear-title-music-resources)
  (clear-short-sound-resources))
