(in-package #:immortal-coil)

(defconstant +virtual-width+ 800)
(defconstant +virtual-height+ 600)
(defconstant +particle-size+ 2)

(defconstant +menu-start-x+ 400.0)
(defconstant +menu-start-y+ 300.0)
(defconstant +title-orbit-radius+ 145.0)

(defparameter *characters-per-second* 11.0)
(defparameter *fade-seconds* 1.2)
(defparameter *menu-fade-seconds* 3.0)
(defparameter *start-confirm-seconds* 0.55)
(defparameter *start-fade-out-seconds* 2.1)
(defparameter *game-fade-in-seconds* 2.8)
(defparameter *game-start-type-delay-seconds* 1.1)
(defparameter *menu-start-text-size* 18)
(defparameter *particle-count* 8)
(defparameter *title-particle-count* 1000)
(defparameter *title-particle-spawn-rate* 70.0)
(defparameter *dialog-script-paths* '("game/opening.lisp"))

(defvar *mode* :menu)
(defvar *menu-elapsed* 0.0)
(defvar *menu-start-state* :idle)
(defvar *menu-start-elapsed* 0.0)
(defvar *game-fade-elapsed* 0.0)
(defvar *borderless-fullscreen-p* nil)
