(in-package #:immortal-coil)

(defconstant +virtual-width+ 1280)
(defconstant +virtual-height+ 720)
(defconstant +virtual-center-x+ (/ +virtual-width+ 2.0))
(defconstant +virtual-center-y+ (/ +virtual-height+ 2.0))
(defconstant +particle-size+ 2)
(defconstant +star-particle-size+ 1)

(defconstant +menu-start-x+ +virtual-center-x+)
(defconstant +menu-start-y+ 410.0)
(defconstant +title-orbit-radius+ 145.0)
(defconstant +title-logo-width+ 900.0)
(defconstant +title-logo-y+ 34.0)

(defparameter *characters-per-second* 11.0)
(defparameter *fade-seconds* 1.2)
(defparameter *menu-fade-seconds* 3.0)
(defparameter *start-confirm-seconds* 0.55)
(defparameter *start-fade-out-seconds* 2.1)
(defparameter *game-fade-in-seconds* 2.8)
(defparameter *game-start-type-delay-seconds* 1.1)
(defparameter *menu-start-text-size* 18)
(defparameter *particle-count* 8)
(defparameter *star-particle-count* 120)
(defparameter *particle-field-fade-seconds* 6.5)
(defparameter *title-particle-count* 1000)
(defparameter *title-particle-spawn-rate* 70.0)
(defparameter *dialog-script-paths* '("game/opening.lisp"))

(defvar *mode* :menu)
(defvar *menu-elapsed* 0.0)
(defvar *menu-start-action* nil)
(defvar *menu-start-state* :idle)
(defvar *menu-start-elapsed* 0.0)
(defvar *game-fade-elapsed* 0.0)
(defvar *quit-requested-p* nil)
(defvar *paused-p* nil)
(defvar *window-mode* :windowed)
(defvar *requested-window-mode* nil)
(defvar *fullscreen-width* +virtual-width+)
(defvar *fullscreen-height* +virtual-height+)
