(in-package #:immortal-coil)

(defun current-monitor-geometry ()
  (let* ((monitor (get-current-monitor))
         (position (make-vector2 0 0)))
    (claylib/ll:get-monitor-position (claylib::c-ptr position) monitor)
    (values (truncate (x position))
            (truncate (y position))
            (get-monitor-width monitor)
            (get-monitor-height monitor))))

(defun enter-fullscreen ()
  (when (is-window-fullscreen-p)
    (toggle-fullscreen))
  (multiple-value-bind (x y width height)
      (current-monitor-geometry)
    (set-window-state +flag-window-undecorated+)
    (set-window-position x y)
    (set-window-size width height)
    (setf *borderless-fullscreen-p* t)))

(defun exit-fullscreen ()
  (when (is-window-fullscreen-p)
    (toggle-fullscreen))
  (multiple-value-bind (x y width height)
      (current-monitor-geometry)
    (clear-window-state +flag-window-undecorated+)
    (set-window-size +virtual-width+ +virtual-height+)
    (set-window-position (+ x (truncate (- width +virtual-width+) 2))
                         (+ y (truncate (- height +virtual-height+) 2)))
    (setf *borderless-fullscreen-p* nil)))

(defun toggle-game-fullscreen ()
  (if (or *borderless-fullscreen-p*
          (is-window-fullscreen-p))
      (exit-fullscreen)
      (enter-fullscreen)))

(defun update-window-controls ()
  (when (is-key-pressed-p +key-f+)
    (toggle-game-fullscreen)))
