(in-package #:immortal-coil)

(defun update-gameplay (dt)
  (update-particles dt)
  (incf (play-state-elapsed *state*) dt)
  (let ((node (current-node)))
    (advance-typewriter node)
    (case (node-kind node)
      (:choice (update-choice-node node))
      (:branch (update-branch-node node))
      (:number (update-number-node node))
      (:string (update-string-node node))
      (:minigame (update-minigame-node node dt))
      (t (update-text-node node)))))

(defun draw-gameplay ()
  (draw-particles)
  (case (node-kind (current-node))
    (:choice (draw-choice-node (current-node)))
    (:branch nil)
    (:number (draw-number-node (current-node)))
    (:string (draw-string-node (current-node)))
    (:minigame (draw-minigame-node (current-node)))
    (t (draw-opening-text-node (current-node)))))
